core/urls.py
from django.conf.urls import patterns, url
from core.views import ObjetivoListView, Objetivo2ListView, ObjetivoMobListView

urlpatterns = patterns('',
    url(r'^$', ObjetivoListView.as_view(), name='dash'),
    url(r'^mob/$', ObjetivoMobListView.as_view(), name='mob'),
    url(r'^list/$', Objetivo2ListView.as_view(), name='list'),
    # Audit log
    url(r'^audit-metas/$', 'core.views.audit_metas', name='audit_metas'),
)

ndmetas/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('core.urls', namespace='objetivo')),
    url(r'^admin/', include(admin.site.urls)),

    # Accounts
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^accounts/change-password/$', 'django.contrib.auth.views.password_change', {'post_change_redirect': '/'}, name='change_password'),
    url(r'^accounts/change-password/done/$', 'django.contrib.auth.views.password_change_done', name='change_password_done'),
)

urlpatterns += staticfiles_urlpatterns()

core/models.py
# coding: utf-8
from django.contrib.auth.models import User
from django.db import models
from audit_log.models.fields import LastUserField
from audit_log.models.managers import AuditLog


# South introspection rules for django-audit-log
from south.modelsinspector import add_introspection_rules

try:
    # Make sure the `to` and `null` parameters will be ignored
    rules = [(
                 (LastUserField,),
                 [],
                 {
                     'to': ['rel.to', {'default': User}],
                     'null': ['null', {'default': True}],
                     },
                 )]

    # Add the rules for the `LastUserField`
    add_introspection_rules(
        rules,
        ['^audit_log\.models\.fields\.LastUserField'],
    )
except ImportError:
    pass


# Create your models here.
class ObjetivoAtivoManager(models.Manager):
    def get_query_set(self):
        return super(ObjetivoAtivoManager, self).get_query_set().filter(ativo=True)

class Objetivo(models.Model):
    titulo = models.CharField(u'Título', max_length=120)
    descricao = models.TextField(blank=True)
    data_inicio = models.DateField(u'Data de início')
    data_fim = models.DateField(u'Data de conclusão')
    ativo = models.BooleanField(default=True)

    # Auditoria
    alterado_por = models.ForeignKey(User, verbose_name='Alterado por', editable=False)
    data_criacao = models.DateTimeField(u'Data de criação', auto_now_add=True)
    data_atualizacao = models.DateTimeField(u'Data de atualização', auto_now=True)

    # Manager
    objects = models.Manager()
    ativos = ObjetivoAtivoManager()

    # Log
    audit_log = AuditLog()

    class Meta:
        ordering = ['id']

    def __unicode__(self):
        return self.titulo


class Servico(models.Model):
    nome = models.CharField(max_length=120)

    # Log
    audit_log = AuditLog()

    def __unicode__(self):
        return self.nome


class Medida(models.Model):
    unidade = models.CharField(max_length=75)

    # Log
    audit_log = AuditLog()

    def __unicode__(self):
        return self.unidade


class ItemObjetivo(models.Model):
    objetivo = models.ForeignKey(Objetivo)
    servico = models.ForeignKey(Servico)
    quantidade = models.IntegerField()
    quantidade_atual = models.IntegerField('Quantidade atual', default=0)
    medida = models.ForeignKey(Medida)

    # Log
    audit_log = AuditLog()

    def porcentagem_concluida(self):
        percentual = self.quantidade_atual * 100 / self.quantidade
        return '{0}'.format(int(percentual))

    def cor_knob(self):

        CORES = {
            'vermelho': '#FF1539',
            'amarelo': '#FFDB15',
            'verde': '#29BC10',
            'dourado': '#CBAE0C',
        }

        if int(self.porcentagem_concluida()) <= 30:
            return CORES['vermelho']
        elif 30 < int(self.porcentagem_concluida()) <= 75:
            return CORES['amarelo']
        elif 75 < int(self.porcentagem_concluida()) < 100:
            return CORES['verde']
        else:
            return CORES['dourado']

    def __unicode__(self):
        return u'{0}% Concluído'.format(float(self.porcentagem_concluida()))

core/views.py
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from core.models import Objetivo, ItemObjetivo
from django.shortcuts import render, redirect

# Create your views here.
class ObjetivoListView(ListView):
    queryset = Objetivo.ativos.all()

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ObjetivoListView, self).dispatch(*args, **kwargs)


class ObjetivoMobListView(ListView):
    queryset = Objetivo.ativos.all()
    template_name = 'core/objetivo_mob_list.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ObjetivoMobListView, self).dispatch(*args, **kwargs)


class Objetivo2ListView(ListView):
    queryset = Objetivo.ativos.all()
    template_name = 'core/objetivo_new_list.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(Objetivo2ListView, self).dispatch(*args, **kwargs)


# Audit log page
@login_required
def audit_metas(request):
    objetivos = Objetivo.objects.all()
    item_objetivos = ItemObjetivo.objects.all()

    return render(request,
        'core/objetivos_audit_metas.html',
        {'objetivos': objetivos, 'item_objetivos': item_objetivos}
    )

ndmetas/templates/core/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="pt-br" >
<head>
    <title>ND Metas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}admin/css/dashboard.css" />
    <!-- Le styles -->
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ STATIC_URL }}core/css/application.css">
    {% block extra_css %}{% endblock %}

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" /> -->
    <script type="text/javascript">window.__admin_media_prefix__ = "{{ STATIC_URL }}admin/";</script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}core/js/jquery.knob.js"></script>
    <script src="{{ STATIC_URL }}core/js/jquery.currency.js"></script>
    <script src="{{ STATIC_URL }}core/js/setup.js"></script>

    <meta name="robots" content="NONE,NOARCHIVE" />
</head>


<body>

<div id="masthead">
    <div class="container">
        <div class="masthead-pad">
            <div class="masthead-text">
                <a href="/" class="logo_nd pull-left"><img src="{{ STATIC_URL }}core/img/logo.png" style="width:150px;" /></a>
                {% if user.is_authenticated %}
                    <ul class="nav nav-pills pull-right" style="margin: 10px 0 0 0">
                        {% if user.is_staff %}<li><a href="{% url admin:index %}">{% trans 'Site administration' %}</a></li>{% endif %}
                        <li><a href="{% url change_password %}">{% trans 'Change password' %}</a></li>
                        <li class="active">
                            <a href="javascript:void(0);" style="cursor: default">
                                <i class="icon-user icon-white"></i>
                                {{ user }}
                            </a>
                        </li>
                        <li>
                            <a style="background-color: #777; color: #fff" href="{% url logout %}">
                                <i class="icon-off icon-white"></i>
                                {% trans 'Log out' %}
                            </a>
                        </li>
                    </ul>
                {% endif %}
            </div> <!-- /.masthead-text -->
        </div>
    </div> <!-- /.container -->
</div>

<div id="content">
<div class="container">
    {% block content %}{% endblock %}
    <hr>
    <div class="footer">
        <p>&copy; ND Engenharia e Software</p>
    </div>
</div> <!-- /container -->
</div>

</body>
</html>

ndmetas/templates/core/objetivo_list.html
{% extends "core/base.html" %}

{% block content %}
    {% for obj in object_list %}
        <div class="row">
            <div class="span12">
                <div class="plan-container best-value">
                    <div class="plan">
                        <div class="plan-header">
                            <div class="plan-title" style="text-align: left; padding-left: 25px">
                                {{ obj.titulo }} - <small style="white-space: nowrap">Até {{ obj.data_fim }}</small>
                            </div> <!-- /plan-title -->
                        </div> <!-- /plan-header -->
                        <div class="plan-features">
                            <ul>
                                <li style="text-align: left">{{ obj.descricao|safe }}</li>
                                <li>
                                    <div>
                                        <div id="d3" style="width: 100%;"></div><br/>
                                        <div class="row-fluid">
                                            {% for item in obj.itemobjetivo_set.all %}
                                                <div class="span3 knob" style="padding-bottom: 10px">
                                                    <h4>{{ item.servico }}</h4>
                                                    <input type="text" value="{{ item.porcentagem_concluida }}" data-width="120" data-fgColor="{{ item.cor_knob }}" data-readOnly="true" class="dial"/>
                                                    {% if item.servico.nome == "Setor Projetos" %}
                                                        <h6><strong><span class="jq-currency">{{ item.quantidade_atual }}</span> / <span class="jq-currency">{{ item.quantidade }}</span></strong><br><span class="muted">{{ item.medida }}</span></h6>
                                                    {% else %}
                                                        <h6><strong><span>{{ item.quantidade_atual }}</span> / <span>{{ item.quantidade }}</span></strong><br><span class="muted">{{ item.medida }}</span></h6>
                                                    {% endif %}
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="plan-actions"></div> <!-- /plan-actions -->
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    <script></script>
{% endblock %}

ndmetas/templates/core/objetivo_new_list.html
{% extends "core/base.html" %}

{% block content %}

    {% for obj in object_list %}
    <div class="row">
        <div class="span12">
            <h3>{{ obj.titulo }} <small style="white-space: nowrap">{{ obj.data_inicio }} até {{ obj.data_fim }}</small></h3>
            <p class="muted">{{ obj.descricao }}</p>
            {% for item in obj.itemobjetivo_set.all %}
            <table class="table table-bordered" style="background-color: #fff">
                <tr>
                    <td>
                        <strong>{{ item.servico }}</strong> - {{ item.quantidade_atual }} {{ item.medida }}{{ item.quantidade_atual|pluralize }}
                        de {{ item.quantidade }} {{ item.medida }}{{ item.quantidade|pluralize }}
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <div class="progress progress-info progress-striped" style="margin-bottom: 0">
                            <div class="bar" style="width: {{ item.porcentagem_concluida }}%">{{ item.porcentagem_concluida|floatformat:"1" }}%</div>
                        </div>
                    </td>
                </tr>
            </table>
            {% endfor %}
        </div>
    </div>
    {% endfor %}

{% endblock %}

ndmetas/templates/core/objetivos_audit_metas.html
<!DOCTYPE html>
<html>
<head>
    <title>Auditoria de Metas</title>
    <style>
        * { margin: 0; padding: 0 }
        body {
            font-family: Tahoma, Arial, sans-serif;
            font-size: 0.8em;
            color: #333;
            padding: 0 10px;
            background-color: #ddddbb;
        }
        table { width: 100%; margin-top: 10px; background-color: #fff }
        caption { background-color: #83ae4e; color: #fff; font-size: 1.3em; padding: 3px }
        th { background-color: #edecd6; white-space: nowrap }
        th, td { border-style: solid; border-color: #ddddbb; border-width: 0 1px 1px 0; padding: 0 5px; margin: 0 }
        th.audit { background-color: #d6e9c6; width: 10% }
        td.audit { background-color: #eeffcc }
    </style>
</head>
<body>

<table>
<caption>Auditoria para Objetivos</caption>
<thead>
    <tr>
        <th class="audit">Usuário</th>
        <th class="audit">Data/Hora</th>
        <th class="audit">Ação</th>
        <th>Título</th>
        <th>Descrição</th>
        <th>Data início</th>
        <th>Data fim</th>
        <th>Ativo?</th>
    </tr>
</thead>
<tbody>
{% for objetivo in objetivos %}
    {% for audit_objetivo in objetivo.audit_log.all %}
        <tr>
            <td class="audit">{{ audit_objetivo.action_user }}</td>
            <td class="audit" style="white-space: nowrap">{{ audit_objetivo.action_date|date:"d/m/Y H:i:s" }}</td>
            <td class="audit">
                {% if audit_objetivo.action_type == 'U' %}Alterado
                {% elif audit_objetivo.action_type == 'I' %}Criado
                {% else %}Removido{% endif %}
            </td>
            <td>{{ audit_objetivo.titulo }}</td>
            <td>{{ audit_objetivo.descricao|linebreaks }}</td>
            <td>{{ audit_objetivo.data_inicio|date:"d/m/Y" }}</td>
            <td>{{ audit_objetivo.data_fim|date:"d/m/Y" }}</td>
            <td>{% if audit_objetivo.ativo %}Sim{% else %}Não{% endif %}</td>
        </tr>
    {% endfor %}
{% endfor %}
</tbody>
</table>

<table>
<caption>Auditoria para Item de Objetivos</caption>
<thead>
    <tr>
        <th class="audit">Usuário</th>
        <th class="audit">Data/Hora</th>
        <th class="audit">Ação</th>
        <th>Objetivo</th>
        <th>Serviço</th>
        <th>Quantidade</th>
        <th>Quantidade atual</th>
        <th>Medida</th>
    </tr>
</thead>
{% for item_objetivo in item_objetivos %}
    {% for audit_item_objetivo in item_objetivo.audit_log.all %}
        <tr>
            <td class="audit">{{ audit_item_objetivo.action_user }}</td>
            <td class="audit" style="white-space: nowrap">{{ audit_item_objetivo.action_date|date:"d/m/Y H:i:s" }}</td>
            <td class="audit">
                {% if audit_item_objetivo.action_type == 'U' %}Alterado
                {% elif audit_item_objetivo.action_type == 'I' %}Criado
                {% else %}Removido{% endif %}
            </td>
            <td>{{ audit_item_objetivo.objetivo.titulo }}</td>
            <td>{{ audit_item_objetivo.servico.nome }}</td>
            <td>{{ audit_item_objetivo.quantidade }}</td>
            <td>{{ audit_item_objetivo.quantidade_atual }}</td>
            <td>{{ audit_item_objetivo.medida.unidade }}</td>
        </tr>
    {% endfor %}
{% endfor %}
</table>

</body>
</html>

ndmetas/templates/mob_layout/main.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8"/>
    <title>ND Metas</title>

    <link rel="stylesheet" type="text/css" href="main.css"/>
    <style type="text/css">
        body { margin: 0 auto; padding-top: 0 }
        body > h1 { margin-bottom: 10px }
        article {background-color: #fff }
        article > h3, article > p { padding: 16px }
        article > h3 { padding-bottom: 0 }
        article > p { padding-top: 0 }
        section { position: relative; float: left; width: 128px; background-color: #f5f5f5; text-align: center; height: 185px }
        section > div.graph-knob { margin-left: 14px }
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!-- Adding "maximum-scale=1" fixes the Mobile Safari auto-zoom bug: http://filamentgroup.com/examples/iosScaleBug/ -->
</head>

<body>
<h1><img src="nd_web.svg" width="150" height="32" title="ND Engenharia e Software"></h1>
<hr>
<article>
    <h3>Título</h3>
    <p>Descrição da meta</p>
    <section>
        <h4>Serviço</h4>
        <div class="graph-knob" data-ident="graph-0" data-color="green" data-percent="75"></div>
        <p>0 / 6<br>unidades</p>
    </section>
    <section>
        <h4>Serviço</h4>
        <div class="graph-knob" data-ident="graph-1" data-color="yellow" data-percent="45"></div>
        <p>1 / 6<br>unidades</p>
    </section>
    <section>
        <h4>Serviço</h4>
        <div class="graph-knob" data-ident="graph-2" data-color="blue" data-percent="65"></div>
        <p>2 / 6<br>unidades</p>
    </section>
    <section>
        <h4>Serviço</h4>
        <div class="graph-knob" data-ident="graph-3" data-color="pink" data-percent="85"></div>
        <p>3 / 6<br>unidades</p>
    </section>
    <section>oi</section>
    <section>oi</section>
    <section>oi</section>
    <section>oi</section>
</article>
<div id="log"></div>
<script type="text/javascript" src="app.js"></script>
</body>

</html>